//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P1_Group> P1_Group { get; set; }
        public virtual DbSet<P1_Record> P1_Record { get; set; }
        public virtual DbSet<P1_Record_Correct> P1_Record_Correct { get; set; }
        public virtual DbSet<P1_User_Account> P1_User_Account { get; set; }
        public virtual DbSet<P1_User_Detail> P1_User_Detail { get; set; }
        public virtual DbSet<P1_Overspend> P1_Overspend { get; set; }
    }
}
