//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class P1_Group
    {
        public int G_id { get; set; }
        public string Gname { get; set; }
        public int U_id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
    
        [JsonIgnore]
        public virtual P1_User_Account P1_User_Account { get; set; }
    }
}
