//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class P1_Record
    {
        public int r_id { get; set; }
        public int hour { get; set; }
        public int minute { get; set; }
        public System.DateTime time { get; set; }
        public string @event { get; set; }
        public string location { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public int weekly { get; set; }
        public bool schedule { get; set; }
        public int user_id { get; set; }

        [JsonIgnore]
        public virtual P1_User_Account P1_User_Account { get; set; }
    }
}
