//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class P1_User_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P1_User_Account()
        {
            this.P1_Group = new HashSet<P1_Group>();
            this.P1_Record = new HashSet<P1_Record>();
            this.P1_Overspend = new HashSet<P1_Overspend>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P1_Group> P1_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P1_Record> P1_Record { get; set; }
        [JsonIgnore]
        public virtual P1_User_Detail P1_User_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P1_Overspend> P1_Overspend { get; set; }
    }
}
